# Generated by Django 2.1.2 on 2019-10-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carnet',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigo_qr',
            field=models.FileField(blank=True, null=True, upload_to='codigos/%Y/%m/%d'),
        ),
    ]
