# Generated by Django 2.1.2 on 2019-10-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191008_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='silla',
            name='estado_lugar',
            field=models.SmallIntegerField(choices=[(3, 'Ocupado'), (1, 'Disponible'), (4, 'Reservado')], default=1),
        ),
    ]
