# Generated by Django 2.1.2 on 2019-10-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191010_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cantidad_verificacion',
            field=models.SmallIntegerField(default=0),
        ),
    ]
