# Generated by Django 2.1.2 on 2019-10-14 03:38

from django.db import migrations

def load_inital_data(apps, schema_editor):
    #Sillas reservadas
    Silla = apps.get_model("api", "Silla")
    pivote = 64
    try:
        grupo_once = [1,2,5,6,7,8,9,11,12,13,14]
        grupo_diez = [3,4,15]
        grupo_nueve = [10]
        for x in range(1, 16):
            letra_inicial = pivote + x
            letra_silla = chr(letra_inicial)
            for i in range(1, 12):
                if x in grupo_diez and i < 11:
                    silla = Silla(
                        no_lugar= i,
                        fila_letra=letra_silla
                    )
                    silla.save()
                elif x in grupo_nueve and i < 10:
                    silla = Silla(
                        no_lugar= i,
                        fila_letra=letra_silla
                    )
                    silla.save()
                elif x in grupo_once:
                    silla = Silla(
                        no_lugar= i,
                        fila_letra=letra_silla
                    )
                    silla.save()
                else:
                    break
    except Exception as e:
        pass
    sillas = Silla.objects.filter(
        fila_letra="A"
    ).update(
        estado_lugar=4
    )

    #Creación de carreras
    Carrera = apps.get_model("api", "Carrera")
    Carrera(nombre="Mercadotecnia y Publicidad").save()
    Carrera(nombre="Contaduría Pública y Auditoría").save()
    Carrera(nombre="Administración de empresas").save()
    Carrera(nombre="Comercio Internacional").save()
    Carrera(nombre="Maestría en Administración de Empresas").save()
    Carrera(nombre="Informática y Administración de Empresas").save()
    #Creación de semestres
    Semestre = apps.get_model("api", "Semestre")
    Semestre(
        numero = 1,
        nombre = "primero"
    ).save()
    Semestre(
        numero = 2,
        nombre = "segundo"
    ).save()
    Semestre(
        numero = 3,
        nombre = "tercero"
    ).save()
    Semestre(
        numero = 4,
        nombre = "cuarto"
    ).save()
    Semestre(
        numero = 5,
        nombre = "quinto"
    ).save()
    Semestre(
        numero = 6,
        nombre = "sexto"
    ).save()
    Semestre(
        numero = 7,
        nombre = "séptimo"
    ).save()
    Semestre(
        numero = 8,
        nombre = "octavo"
    ).save()
    Semestre(
        numero = 9,
        nombre = "noveno"
    ).save()
    Semestre(
        numero = 10,
        nombre = "décimo"
    ).save()
    Semestre(
        numero = 11,
        nombre = "undécimo"
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_configuracion'),
    ]

    operations = [
        migrations.RunPython(load_inital_data)
    ]
